// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ81J28rTpMj9ot5VgeQVReHBIAm1Xlqs',
    appId: '1:271680876527:web:51a59d1356416d8bbc501a',
    messagingSenderId: '271680876527',
    projectId: 'socialmedia-c1e93',
    authDomain: 'socialmedia-c1e93.firebaseapp.com',
    storageBucket: 'socialmedia-c1e93.appspot.com',
    measurementId: 'G-WC7S2YSR3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB8P9b82q_X3duToGkSL1VnywFtvpfxTc',
    appId: '1:271680876527:android:ebc094674b7cd8e8bc501a',
    messagingSenderId: '271680876527',
    projectId: 'socialmedia-c1e93',
    storageBucket: 'socialmedia-c1e93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLfMx8gqcMSUI90qr8qaUMrLZ5lDVErYs',
    appId: '1:271680876527:ios:395eab0997f79b21bc501a',
    messagingSenderId: '271680876527',
    projectId: 'socialmedia-c1e93',
    storageBucket: 'socialmedia-c1e93.appspot.com',
    iosClientId: '271680876527-i9u6msol9jq8avqg2mji0dq6ke4pk1e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.techMedia',
  );
}
